### ISSUE TITLE
monitor bloom filter memory usage

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla-monitoring#2225] opened 2024-03-18 17:02 UTC
Please make sure that this is a feature request. 

**System information**
- Scylla version (you are using): any
- Are you willing to contribute it (Yes/No): no

**Describe the feature and the current behavior/state.**

I want the memory panel to include this expression: sum(scylla_sstables_bloom_filter_memory_size) by (instance, shard)

**Who will benefit with this feature?**

People who have large bloom filters

**Any Other info.**

The universe is almost 14 billion years old

**Comment by mykaul** [comment] 2024-03-18 17:39
Already implemented via https://github.com/scylladb/scylla-monitoring/pull/2223 , no?

**Comment by amnonh** [comment] 2024-03-19 06:36
Closing as duplicate of #2219, please re-open if something is missing

**Closed as completed by amnonh** 2024-03-19 06:36 UTC
Labels: enhancement
