### ISSUE TITLE
autocomplete is gone?

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla-monitoring#840] opened 2020-03-02 12:28 UTC
In our 3.2 stack, grafana doesn't seem to be autocompleting metric names anymore.

**Comment by tzach** [comment] 2020-03-02 13:54
Are you using Firefox?

**Comment by glommer** [comment] 2020-03-02 14:20
chrome , as before

**Comment by amnonh** [comment] 2020-03-10 12:54
I've just tested it with the latest version, as you can see auto-complete works.

![Screenshot from 2020-03-10 14-51-31](https://user-images.githubusercontent.com/2118079/76314062-cc6a4600-62de-11ea-9cdf-78b95763af59.png)

I guess something else was wrong in the environment, maybe there was no data at that point?

**Comment by glommer** [comment] 2020-03-10 13:44
Thanks for taking a look at this, @amnonh 

It certainly had data.

@dyasny you were the one that set up the environment for 3.2 that we used to take a look at the recent issue we investigated together.

Anything you did different that would be worth mentioning?

@amnonh is autocomplete by any chance a plugin? Maybe the plugin failed to install ?

**Comment by dyasny** [comment] 2020-03-10 13:47
No difference. I always use either `-v 2019.1` or `-v latest`  and always get the code from git and switch to the latest branch

**Comment by dyasny** [comment] 2020-03-10 13:48
This specific environment is lacking `node_exporter` metrics, maybe autocomplete doesn't work where there isn't a full expected set available?

**Comment by amnonh** [comment] 2020-03-24 12:48
@dyasny is this still an issue? I couldn't reproduce and have little to work by.
Did you see any errors in `docker logs agraf` ?

Did it happen on other systems than the one you reported?

**Comment by amnonh** [comment] 2020-04-01 13:21
Closing as not reproducible, please open again if you need to

**Closed as completed by amnonh** 2020-04-01 13:21 UTC
