### ISSUE TITLE
Improve the README.md file with missing steps and verifications

### ISSUE THREAD

**Issue by gnumoreno** [scylladb/scylla-monitoring#511] opened 2019-02-20 21:25 UTC
Update the path to the relevant Doc page: https://docs.scylladb.com/operating-scylla/monitoring/monitoring_stack/

## Problem
Some steps and a notice about absolute path are missing.

## Suggest a fix

Add the following steps:

#### Disable SELinux
`sudo vi /etc/selinux/config`
```
SELINUX=disabled
```
Restart server:
`sudo shutdown -r now`

Reference documentation: https://linuxize.com/post/how-to-disable-selinux-on-centos-7/

#### Link to docker installation documents (it covers all distributions)
https://docs.docker.com/install/

#### Make sure docker will be started automatically and that it is up and running
```
sudo systemctl enable docker
sudo systemctl start docker
sudo systemctl status docker
```

#### Manage Docker as a non-root user (docker post-installation steps)

```
sudo groupadd docker
USER=`whoami`
sudo usermod -aG docker $USER
# logoff from the current shell and login again
# test with
docker ps -a
```
Reference documentation: https://docs.docker.com/install/linux/linux-postinstall/

#### Add disclaimer about -d parameter

When using `./start-all.sh` script with `-d` parameter to pass a prometheus data_dir, the argument for the parameter should be an absolute path. Ex.:

`-d /home/ec2-user/scylla-grafana-monitoring-scylla-monitoring-2.1/data`
and not a relative path

Reference: #508

**Comment by tzach** [comment] 2019-02-21 07:25
About SELinux issue: it was reported in the past: #483 But I failed to reproduce it
I have no doubt there is a real issue here, but I'm not sure its related to SELinux, why, and if there is a better way to solve it.

**Comment by amnonh** [comment] 2019-02-21 07:32
In general, I'm in favor of keeping the README up to date, the only issue is that we already updated the documentation and now have a duplication that needs to be updated as well.

I think it's better to keep the information in a single place (The documentation) remove most of the stuff in the README and make sure the link to the documentation is clear.
@tzach your thoughts?

**Comment by tzach** [comment] 2019-02-21 07:35
Make sense to keep most of the docs in the doc page.
Readme can be basic and mostly about development, not usage.
See https://github.com/docker/docker-ce for example.

**Comment by gnumoreno** [comment] 2019-02-21 13:27
@tzach About SELinux, I had a problem with a customer and consulted with @amnonh 
The solution was to disable SELinux

Error:
```
t=2019-02-20T18:02:46+0000 lvl=eror msg="can't read datasource provisioning files from directory" logger=provisioning.datasources path=/var/lib/grafana/provisioning/datasources
t=2019-02-20T18:02:46+0000 lvl=info msg="Initializing PluginManager" logger=server
t=2019-02-20T18:02:46+0000 lvl=info msg="Starting plugin search" logger=plugins
t=2019-02-20T18:02:46+0000 lvl=warn msg="Could not scan dir \"/var/lib/grafana/plugins\" error: open /var/lib/grafana/plugins: permission denied"
t=2019-02-20T18:02:46+0000 lvl=info msg="Initializing TracingService" logger=server
t=2019-02-20T18:02:46+0000 lvl=eror msg="can't read dashboard provisioning files from directory" logger=provisioning.dashboard path=/var/lib/grafana/provisioning/dashboards
t=2019-02-20T18:02:46+0000 lvl=info msg="Initializing Stream Manager"
t=2019-02-20T18:02:46+0000 lvl=info msg="HTTP Server Listen" logger=http.server address=0.0.0.0:3000 protocol=http subUrl= socket=
```

**Comment by tzach** [comment] 2019-02-21 13:47
Its a possible solution, but hopefully we can also suggest something more granular.
Is this related to running docker with root?
@gnumoreno can you please try to reproduce?

**Comment by gnumoreno** [comment] 2019-02-21 18:23
@tzach it is not. The error I pasted was for running with sudo. After doing the docker post-install steps without sudo, same error.

**Comment by tzach** [comment] 2019-02-21 18:26
Thanks, still not clear why I could not reproduce, but since its repeating issue, let's add this as an inline troubleshooting phase.
.

**Comment by amnonh** [comment] 2019-04-25 09:00
@tzach I think we cover it all in the documentation, should we remove things from the README or just close this issue?

**Comment by amnonh** [comment] 2019-12-02 14:11
@tzach ping

**Comment by tzach** [comment] 2019-12-02 19:06
I'm fine with adding this to the docs. Please send a PR

**Comment by amnonh** [comment] 2019-12-02 20:25
See my previous comment, it's already covered in the doc

**Comment by amnonh** [comment] 2020-04-21 05:57
Closing as no longer relevant

**Closed as completed by amnonh** 2020-04-21 05:57 UTC
