### ISSUE TITLE
query processing would load too many samples into memory in query execution

### ISSUE THREAD

**Issue by AdamStawarz** [scylladb/scylla-monitoring#1367] opened 2021-04-21 13:14 UTC
We should consider add some documentation about "--query.max-samples". This value should be increased every time when our customers see: " query processing would load too many samples into memory in query execution "

**System information**
Zendesk: 1675
Monitoring: 3.6

**Describe the situation now**
Issue:  "query processing would load too many samples into memory in query execution"
![image](https://user-images.githubusercontent.com/11996012/115558057-9d305180-a2b2-11eb-8864-e2241c0005d9.png)

**What needs to be there**
from prometheus release notes:
The second feature is that there is now a limit on the number of samples a query can have in memory at once, making it possible to stop massive queries that take too much RAM and threaten to OOM your Prometheus. This can be adjusted with the --query.max-samples flag. Each sample uses 16 bytes of memory, however keep in mind there's more than just active samples in memory for a query.
https://www.robustperception.io/new-features-in-prometheus-2-5-0

e.g. if I don't want prometheus to take more than 4G of ram PER QUERY (but bear in mind more queries like that can be there)
4 * 1024 * 1024 * 1024 / 16 = 268435456 max samples, if you don't want this scan query to take more than 4G ram

**Comment by amnonh** [comment] 2021-04-25 08:22
I see that it happens in the latencies queries even though the time range is small, maybe we need to use recording rules.

**Comment by tzach** [comment] 2021-06-09 07:27
@amnonh why is this a doc issue?

**Comment by amnonh** [comment] 2021-06-09 07:31
This issue is asking to change the documentation

**Comment by amnonh** [comment] 2022-02-08 17:23
I'm closing this issue in favor of actually handling the root cause

**Closed as completed by amnonh** 2022-02-08 17:23 UTC
Labels: documentation
