### ISSUE TITLE
Grafana fails to load alertmanager plugin  "Skipping loading plugin due to problem with signature"

### ISSUE THREAD

**Issue by askeydeteque** [scylladb/scylla-monitoring#1893] opened 2023-02-15 21:32 UTC
Installation
Installed by downloading this link https://github.com/scylladb/scylla-monitoring/archive/refs/tags/scylla-monitoring-4.2.1.tar.gz
and running the ./start-all.sh command.
Scylla Monitoring Stack 4.2.1

When doing the same installation with Scylla Monitoring Stack 4.2.0 there are no issues.
When using Scylla Monitoring Stack 4.2.1, Grafana gives the error that it cannot access the alertmanager plugin. When I look in the logs I see this line:

`logger=plugin.loader t=2023-02-15T20:52:48.354522775Z level=warn msg="Skipping loading plugin due to problem with signature" pluginID=camptocamp-prometheus-alertmanager-datasource status=unsigned`

If I add this parameter to the "start-all.sh" command the alertmanager plugin loads without issue

`'-c "GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=camptocamp-prometheus-alertmanager-datasource"`

**Comment by mykaul** [comment] 2023-02-16 08:07
What version of the plugin are we using? It's supposed to be signed - see https://github.com/camptocamp/grafana-prometheus-alertmanager-datasource/issues/108

**Comment by mykaul** [comment] 2023-02-16 08:10
https://github.com/scylladb/scylla-monitoring/blob/f4534b25426d42692b1f8d6d9b7532915074c7bf/grafana/plugins/camptocamp-prometheus-alertmanager-datasource/dist/plugin.json shows that we use maybe an older version. Perhaps we need to update?

**Comment by amnonh** [comment] 2023-02-16 09:14
This is confusing because we are already allow loading the plugi

**Comment by amnonh** [comment] 2023-02-16 09:22
I just did a clean install and couldn't reproduce.
Maybe there's something wrong with the installation (though I don't have an idea how can that happend).

What is the ./start-all.sh command you used?

**Comment by askeydeteque** [comment] 2023-02-16 13:28
From my script before upgrading this was my full command start-all.sh:

```
./start-all.sh \
	-d /data/prometheus-scylla \
	-s /root/monitoring/configs/prometheus/scylla_servers.yml \
	-b "--storage.tsdb.retention.time=365d" \
	-b "--storage.tsdb.wal-compression" \
	-c "GF_SERVER_DOMAIN=example.com" \
	-c "GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s/scylla-monitoring/" \
	-c "GF_SERVER_SERVE_FROM_SUB_PATH=true" \
	-c "GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=scylladb-scylla-datasource
```

This worked on 4.2.0. When I upgraded to 4.2.1 this no longer worked. It seems because I was overriding the "GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS" variable that would normally allow "camptocamp-prometheus-alertmanager-datasource" to be unsigned. There seems to be an issue with the "camptocamp-prometheus-alertmanager-datasource" signature between 4.2.0 and 4.2.1

**Comment by askeydeteque** [comment] 2023-02-16 13:34
On a fresh install without the "GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS" setting everything works, but I get the warning: 
```
logger=plugin.signature.validator t=2023-02-16T13:18:54.270550376Z level=warn msg="Permitting unsigned plugin. This is not recommended" pluginID=camptocamp-prometheus-alertmanager-datasource pluginDir=/var/lib/grafana/plugins/camptocamp-prometheus-alertmanager-datasource/dist
```

**Comment by mykaul** [comment] 2023-02-16 13:40
> On a fresh install without the "GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS" setting everything works, but I get the warning:
> 
> ```
> logger=plugin.signature.validator t=2023-02-16T13:18:54.270550376Z level=warn msg="Permitting unsigned plugin. This is not recommended" pluginID=camptocamp-prometheus-alertmanager-datasource pluginDir=/var/lib/grafana/plugins/camptocamp-prometheus-alertmanager-datasource/dist
> ```

So we should close this issue and open a separate, about this warning and the (possible) need to update the plugin.

**Comment by amnonh** [comment] 2023-02-16 13:49
Closing as not a bug, the warning you are seeing is becasue we allow to load the plugin, I will open an issue for upgrading the plugin

**Closed as completed** 2023-02-16 13:49 UTC
Labels: bug
