### ISSUE TITLE
Dashboard Screenshot feature didn't worked, Please check the screen shot ! 

### ISSUE THREAD

**Issue by techsurfer** [scylladb/scylla-monitoring#2106] opened 2023-11-02 14:49 UTC
![Screenshot 2023-11-02 at 9 48 32 AM](https://github.com/scylladb/scylla-monitoring/assets/8341677/44b09191-892c-4f0f-980a-614c1e5a9e83)
scylla-version=2023.1
monitoring-version=4.4.5
dashboard=overview-2023-1

**Comment by amnonh** [comment] 2023-11-05 09:58
Duplicate of #2097

**Closed as completed by amnonh** 2023-11-05 09:58 UTC
