### ISSUE TITLE
avg function across multiple scheduling group

### ISSUE THREAD

**Issue by ebenzecri** [scylladb/scylla-monitoring#2012] opened 2023-06-19 18:42 UTC
Scylla-Monitoring Version: 4.4.0

### Issue
_Note: This issue was reported by one of our customers._

`avg(rlatencyp99{by="cluster", cluster=~"$cluster|$^",scheduling_group_name=~"$sg"}>0)`. But why? It's just wrong. This metric doesn't represent anything meaningful.

**Comment by mykaul** [comment] 2023-06-20 07:56
> Note: This issue was reported by one of our customers.

Issues reported by customers should be filed @ https://github.com/scylladb/scylla-enterprise/issues

**Comment by amnonh** [comment] 2023-06-21 13:17
The idea was to choose a scheduling group first.

@ebenzecri please add dashbaord and panels when opening an issue

**Comment by amnonh** [comment] 2023-07-12 09:03
Closing as duplicate of #1989

**Closed as completed by amnonh** 2023-07-12 09:03 UTC
Labels: bug
