### ISSUE TITLE
Unable to drive the metrics to the Graphana dashboard

### ISSUE THREAD

**Issue by eyalgutkind** [scylladb/scylla-monitoring#60] opened 2016-09-22 21:15 UTC
Trying to monitor an on-premise setup of 3 servers.
CentOS 7.2, Kernel 3.18.4. 
The servers are configured with dual networks, 12.9.31.x high speed network connecting the scylla servers communication
10.9.31.x is the slow, ssh network used also for the monitoring traffic.
Setup is using Scylla 1.3, collectd.conf and scylla.conf are attached.
Setting the exporter looks successful and reaching to the data through the URL works.
However,
When looking on the Graphana monitor no info is visible. the servers are running loads.
Is there anything missing here?
![image](https://cloud.githubusercontent.com/assets/17868115/18766126/8cab4a06-80cd-11e6-9ba8-6a8fe18aa877.png)

The exporter command on each server is:
./collectd_exporter -collectd.listen-address="0.0.0.0:65534" &

prometheus yml setting:
[root@localhost ~]# cat scylla-grafana-monitoring/prometheus/prometheus.yml
global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'scylla-monitor'

scrape_configs:
- job_name: scylla
  honor_labels: true
  static_configs:
  - targets: ['10.9.31.182:9103', '10.9.31.183:9103', '10.9.31.184:9103']

Started the server with:
root@localhost scylla-grafana-monitoring]# docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
[root@localhost scylla-grafana-monitoring]# ./start-all.sh 
4d156596f38e536e9ebc24986656f872c50a2541f2668014c69db50afc7b8739
10d3cb213368da71f7793dd962e14960efdb26a2ecc57845d56acb7c7175785d
HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8
Set-Cookie: grafana_sess=2ce4fc7c24a6d04f; Path=/; HttpOnly
Date: Thu, 22 Sep 2016 19:03:41 GMT
Content-Length: 37

{"id":1,"message":"Datasource added"}HTTP/1.1 100 Continue

HTTP/1.1 200 OK
Content-Type: application/json
Set-Cookie: grafana_sess=58ce57e2e35dea80; Path=/; HttpOnly
Date: Thu, 22 Sep 2016 19:03:41 GMT
Content-Length: 64

{"slug":"scylla-cluster-metrics","status":"success","version":0}HTTP/1.1 100 Continue

HTTP/1.1 200 OK
Content-Type: application/json
Set-Cookie: grafana_sess=90d44045c2d53a01; Path=/; HttpOnly
Date: Thu, 22 Sep 2016 19:03:41 GMT
Content-Length: 67

{"slug":"scylla-per-server-metrics","status":"success","version":0}HTTP/1.1 100 Continue

HTTP/1.1 200 OK
Content-Type: application/json
Set-Cookie: grafana_sess=49db89a8e86b16c9; Path=/; HttpOnly
Date: Thu, 22 Sep 2016 19:03:41 GMT
Content-Length: 68

The data connection on Graphana:
![image](https://cloud.githubusercontent.com/assets/17868115/18766297/60b38962-80ce-11e6-88fc-0d7d6ead297d.png)

[collectd_conf.txt](https://github.com/scylladb/scylla-grafana-monitoring/files/488368/collectd_conf.txt)
[scylla_conf.txt](https://github.com/scylladb/scylla-grafana-monitoring/files/488369/scylla_conf.txt)

**Comment by tzach** [comment] 2016-09-25 16:52
@eyalgutkind from the metrics on the Scylla server side (port 9103) its look like you are only getting collectd_exporter metrics, not scylla metrics, like reactor or lsa.
Please check the scylla side config, as detailed here
https://github.com/scylladb/scylla/wiki/Monitor-Scylla-with-Prometheus-and-Grafana#setting-scylla

in particular, the /etc/collectd.d/scylla.conf file
make sure to restart collectd service after you update the file, and make sure collectd runs

**Comment by eyalgutkind** [comment] 2016-09-26 03:03
@tzach This is the information I have on the scylla.conf file:
LoadPlugin network
LoadPlugin disk
LoadPlugin interface
LoadPlugin unixsock
LoadPlugin df
LoadPlugin processes
<Plugin network>
        Listen "127.0.0.1" "25826"
        Server "127.0.0.1" "65534"
        Forward true
</Plugin>
<Plugin disk>
</Plugin>
<Plugin interface>
</Plugin>
<Plugin "df">
  FSType "xfs"
  IgnoreSelected false
</Plugin>
<Plugin unixsock>
    SocketFile "/var/run/collectd-unixsock"
    SocketPerms "0666"
</Plugin>
<Plugin processes>
    Process "scylla"
</Plugin>

I'm able to get some information, but other is missing, for example the total request information is missing, although I do have some load on the servers.
![image](https://cloud.githubusercontent.com/assets/17868115/18821435/ed2dcb08-835a-11e6-9002-73aa39a95538.png)

**Comment by tzach** [comment] 2016-09-26 05:48
@eyalgutkind we made some progress. Now scylla to generate metrics, and monitoring server gets them, which make the problem harder to understand.
Can you please go back to scylla server:9103/metrics and look for `transport_total_requests` ?
If its missing the issue is on the scylla side

**Comment by tzach** [comment] 2016-09-26 07:12
@eyalgutkind the problem is in Grafana dashboard
Adding Thrift support in https://github.com/scylladb/scylla-grafana-monitoring/pull/55 broke the dashboard
The temp bypass is to update the chart
from

```
sum(irate(collectd_transport_total_requests{type="requests_served"}[30s])) by (instance) + sum(irate(collectd_thrift_total_requests{type="served"}[30s])) by (instance)
```

to

```
sum(irate(collectd_transport_total_requests{type="requests_served"}[30s])) by (instance)
```

I will look into it and send a PR soon

**Comment by tzach** [comment] 2016-09-26 08:41
@eyalgutkind on a second look, the problem was solved not by updating the query, rather by editing and refresh. Try to reload the dashboard

**Comment by eyalgutkind** [comment] 2016-09-26 18:16
@tzach so the current package is not backward compatible?

**Comment by tzach** [comment] 2016-09-26 18:52
@eyalgutkind what do you mean? for Scylla 1.2? it should.

**Comment by tzach** [comment] 2017-02-16 10:24
@eyalgutkind I'm closing this issue since its not relevant anymore.
The project now supports dashboard per Scylla release.
Please reopen if the problem return.

**Closed as completed by tzach** 2017-02-16 10:24 UTC
