### ISSUE TITLE
No Data found in some dashboard

### ISSUE THREAD

**Issue by ksunil6266** [scylladb/scylla-monitoring#1634] opened 2021-12-29 05:09 UTC
*Installation details*
Panel Name: All
Dashboard Name: Keyspace, alternator, connection, large row panels
Scylla-Monitoring Version: (3.9.0)
Scylla-Version: 4.5.2

Hi Team,

I am using Scylla Monitoring Stack Without Docker and set up using the below link.
https://monitoring.docs.scylladb.com/stable/install/monitor_without_docker.html
but there are dashboards in which no data occurs like Keyspace, alternator, connection, large row panels, etc. and found no error except this in grafana.
lvl=warn msg="Not saving new dashboard due to restricted database access" logger=provisioning.dashboard type=file name=NAME provisioner=NAME file=/var/lib/grafana/dashboards/ver_4.5/scylla-os.4.5.json folderId=1

**Comment by amnonh** [comment] 2021-12-29 07:25
hi @ksunil6266 You are witnessing multiple issues:
* Alternator data is only valid if you are using Alternator (https://www.scylladb.com/alternator/)
* The keyspace dashboard needs to have the those metrics enable (See #1560)
* Last, the Connection, large row panels uses Scylla plugin to read from Scylla's table directly, I assume it's not installed or not configured correctly.
This is not a bug but I open some issue about better explenation #1636 #1635

**Comment by amnonh** [comment] 2021-12-29 07:26
Closing as not a bug

**Closed as completed by amnonh** 2021-12-29 07:26 UTC
Labels: bug
