### ISSUE TITLE
Scylla Monitoring Does not show "Last Repair" correctly

### ISSUE THREAD

**Issue by anand-chandrashekar** [scylladb/scylla-monitoring#2069] opened 2023-09-27 14:23 UTC
*Installation details*
Panel Name: "Last Repair"
Dashboard Name: Scylla Manager Metrics
Scylla-Monitoring Version: 4.3.4
Scylla-Version: 2022.2.13-0.20230824.575d727536c7

I ran repairs a couple of time via sctool. I can see successful runs.
```
field-cloud-key@anand-gcp-sc-1-monitor:~$ sctool tasks
Cluster: anand-gcp-sc-1 (a014c4ad-4d1c-439a-a3b8-248c539123e5)
╭─────────────────────────────────────────────┬──────────────┬────────┬──────────┬─────────┬───────┬──────────────┬────────────┬────────┬───────────────╮
│ Task                                        │ Schedule     │ Window │ Timezone │ Success │ Error │ Last Success │ Last Error │ Status │ Next          │
├─────────────────────────────────────────────┼──────────────┼────────┼──────────┼─────────┼───────┼──────────────┼────────────┼────────┼───────────────┤
│ healthcheck/cql                             │ @every 15s   │        │ Etc/UTC  │ 7267    │ 0     │ 8s ago       │            │ DONE   │ in 6s         │
│ healthcheck/alternator                      │ @every 15s   │        │ Etc/UTC  │ 7267    │ 0     │ 8s ago       │            │ DONE   │ in 6s         │
│ healthcheck/rest                            │ @every 1m0s  │        │ Etc/UTC  │ 1816    │ 0     │ 56s ago      │            │ DONE   │ in 3s         │
│ repair/564c7943-5c44-481a-8bd3-73a3ae16db38 │              │        │ Etc/UTC  │ 1       │ 0     │ 9h25m51s ago │            │ DONE   │               │
│ repair/all-weekly                           │ 0 23 * * SAT │        │ Etc/UTC  │ 0       │ 0     │              │            │ NEW    │ in 3d8h56m34s │
│ repair/db79165f-c58e-4305-98b2-834bb2956d51 │              │        │ Etc/UTC  │ 1       │ 0     │ 9h18m52s ago │            │ DONE   │               │
╰─────────────────────────────────────────────┴──────────────┴────────┴──────────┴─────────┴───────┴──────────────┴────────────┴────────┴───────────────╯
field-cloud-key@anand-gcp-sc-1-monitor:~$
```

However, scylla monitoring shows "Never" in the last repair even if I expand the monitoring window enough (24 hours).

![image](https://github.com/scylladb/scylla-monitoring/assets/6860841/a12573b6-d0e4-48e0-ae91-6f9cb0a6b88b)

This is a 9 node cluster spread across three zones. Nodetool status is as below (ip addresses are retracted).

```
Datacenter: us-east1
====================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address       Load       Tokens       Owns    Host ID                               Rack
UN  x  334.71 MB  256          ?       47446c60-3fc7-4977-9266-2e01568bc753  d
UN  x  397.95 MB  256          ?       8ce247a0-5a99-4ab2-b3b3-8f59c5beb934  d
UN  x  349.33 MB  256          ?       4723ac9a-948f-44d7-ab68-77784ae4eaf0  b
UN  x 413.16 MB  256          ?       11a6d466-59ad-4753-9435-51c10130a1ff  d
UN  x 405.64 MB  256          ?       6a073a20-38aa-4f78-a501-a01d10da120b  b
UN  x 368.74 MB  256          ?       6cc310f2-8c97-4d3d-ae2f-e5d0d9912587  c
UN  x 390.99 MB  256          ?       8354aead-7dcb-4f45-9119-f1bbe43287bb  c
UN  x 423.93 MB  256          ?       6d7f4d01-3073-42c3-ad77-aa5592bf7c07  b
UN  x 390.53 MB  256          ?       4dd2a029-a346-4373-a028-f8ff351c30da  c
```
cc: @vladzcloudius @gcarmin

**Comment by gcarmin** [comment] 2023-09-27 14:29
@anand-chandrashekar   - 

1. what version of Scylla manager 
2. Can you please upgrade monitoring to 4.4.4? 

And rerun repair from scratch

**Comment by anand-chandrashekar** [comment] 2023-09-27 14:32
1. Scylla Manager Version:
```
Client version: 3.0.2-0.20221128.23e30739
Server version: 3.0.2-0.20221128.23e30739
```
Will upgrade and report.

**Comment by anand-chandrashekar** [comment] 2023-09-27 15:39
Updated to 4.4.4.
![image](https://github.com/scylladb/scylla-monitoring/assets/6860841/0a9936c3-ed8d-4130-b4ec-f99cba95fc12)

Ran repair again.
```
Cluster: anand-gcp-sc-1 (a014c4ad-4d1c-439a-a3b8-248c539123e5)
╭─────────────────────────────────────────────┬──────────────┬────────┬──────────┬─────────┬───────┬───────────────┬────────────┬────────┬───────────────╮
│ Task                                        │ Schedule     │ Window │ Timezone │ Success │ Error │ Last Success  │ Last Error │ Status │ Next          │
├─────────────────────────────────────────────┼──────────────┼────────┼──────────┼─────────┼───────┼───────────────┼────────────┼────────┼───────────────┤
│ healthcheck/cql                             │ @every 15s   │        │ Etc/UTC  │ 7614    │ 0     │ 3s ago        │            │ DONE   │ in 11s        │
│ healthcheck/alternator                      │ @every 15s   │        │ Etc/UTC  │ 7614    │ 0     │ 3s ago        │            │ DONE   │ in 11s        │
│ healthcheck/rest                            │ @every 1m0s  │        │ Etc/UTC  │ 1903    │ 0     │ 33s ago       │            │ DONE   │ in 26s        │
│ repair/564c7943-5c44-481a-8bd3-73a3ae16db38 │              │        │ Etc/UTC  │ 1       │ 0     │ 10h59m31s ago │            │ DONE   │               │
│ repair/all-weekly                           │ 0 23 * * SAT │        │ Etc/UTC  │ 0       │ 0     │               │            │ NEW    │ in 3d7h22m54s │
│ repair/c332ad01-d74a-495f-ad3e-1daa9bd4ed22 │              │        │ Etc/UTC  │ 1       │ 0     │ 1m5s ago      │            │ DONE   │               │
│ repair/db79165f-c58e-4305-98b2-834bb2956d51 │              │        │ Etc/UTC  │ 1       │ 0     │ 10h52m32s ago │            │ DONE   │               │
╰─────────────────────────────────────────────┴──────────────┴────────┴──────────┴─────────┴───────┴───────────────┴────────────┴────────┴───────────────╯
```

Still nothing on the dashboard.
![image](https://github.com/scylladb/scylla-monitoring/assets/6860841/2382f0f6-32cb-48fa-8a07-3e4fdaefbf83)

@gcarmin FYI. Please let me know in case I should try anything more.

**Comment by gcarmin** [comment] 2023-09-27 15:43
Did you upgrade the scylla manager as well?

**Comment by anand-chandrashekar** [comment] 2023-09-27 15:54
No, I didn't.

**Comment by gcarmin** [comment] 2023-09-27 16:08
@anand-chandrashekar so.please make sure yo are using latest versuon for Scylla, Scylla manager and Scylla monitoring.

**Comment by anand-chandrashekar** [comment] 2023-09-28 06:53
I updated manager as well and I could see the last repair. This is not a bug.
![image](https://github.com/scylladb/scylla-monitoring/assets/6860841/a01d18ed-dc21-4f48-acb9-8715f5a89d3b)

**Comment by tarzanek** [comment] 2023-09-29 08:13
also you can always check what that metric means:
https://github.com/scylladb/scylla-monitoring/blob/master/grafana/scylla-manager.template.json#L170
and find respective entry either in prometheus :9090 (to see if it was collected)
or directly on manager (it exports metrics on certain port)

also version wise you should use appropriate version of manager dashboard using -M
(and compat wise: https://monitoring.docs.scylladb.com/stable/reference/matrix.html )

closing as not a bug

**Closed as completed by tarzanek** 2023-09-29 08:13 UTC
