### ISSUE TITLE
Fail to error when data dir doesn't exist

### ISSUE THREAD

**Issue by pveentjer** [scylladb/scylla-monitoring#1414] opened 2021-06-02 08:03 UTC
Scylla-Monitoring Version: 3.7.0

If the scylla-monitor is started with
```
start-all.sh -d <somedir>
```
And the somedir doesn't exist, there is no error. 

I have been banging my head for a few hours why Scylla monitor wasn't able to show the results of the collected data. And then I figured out that the directory name was not correct.

The problem with the start-all.sh is that you need to run this command from the scylla-monitoring directory. 

In my script which automates a few things, I do a chdir to the scylla-monitoring directory, run start-all.sh using the provided data-directory and then chdir back to the original directory.  But I failed to convert the relative path of the data directory into an absolute path. So I was trying to start scylla-monitoring with a non existing directory.

**Comment by amnonh** [comment] 2021-06-02 12:11
if the directory does not exist, start-alls.sh should create it, are you sure it's not there? maybe you gave a relative path when you run start-all.sh?

**Comment by amnonh** [comment] 2021-06-02 13:52
I'm unable to reproduce this, closing, please re-open with the printout of the call to start-all.sh

**Closed as completed by amnonh** 2021-06-02 13:52 UTC
Labels: bug

**Comment by pveentjer** [comment] 2021-06-03 08:31
The fact that the missing directory is created explain it. So somewhere on my drive I have a bunch of unwanted directories :)

Yes. I gave the relative path; that was an error I made. But I have been wondering why Scylla monitoring was not showing my collected metrics or why I didn't get an error on startup. But if the directory is automatically created..
