### ISSUE TITLE
version 3.5 - failing to start aprom

### ISSUE THREAD

**Issue by dyasny** [scylladb/scylla-monitoring#1099] opened 2020-11-02 17:45 UTC
*Installation details*
Panel Name:
Dashboard Name:
Scylla-Monitoring Version: (can be found at the buttom of the overview dashboard) 3.5
Scylla-Version: 2020.1
CentOS 8.2
Docker CE

```
[field-cloud-key@dyasny-97-monitor ~]$ sudo docker logs aprom
level=info ts=2020-11-02T17:39:52.646Z caller=main.go:330 msg="Starting Prometheus" version="(version=2.15.2, branch=HEAD, revision=d9613e5c466c6e9de548c4dae1b9aabf9aaf7c57)"
level=info ts=2020-11-02T17:39:52.646Z caller=main.go:331 build_context="(go=go1.13.5, user=root@688433cf4ff7, date=20200106-14:50:51)"
level=info ts=2020-11-02T17:39:52.646Z caller=main.go:332 host_details="(Linux 4.18.0-193.14.2.el8_2.x86_64 #1 SMP Sun Jul 26 03:54:29 UTC 2020 x86_64 08625ef05623 (none))"
level=info ts=2020-11-02T17:39:52.646Z caller=main.go:333 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2020-11-02T17:39:52.646Z caller=main.go:334 vm_limits="(soft=unlimited, hard=unlimited)"
level=error ts=2020-11-02T17:39:52.647Z caller=query_logger.go:85 component=activeQueryTracker msg="Error opening query log file" file=data/queries.active err="open data/queries.active: permission denied"
panic: Unable to create mmap-ed active query log

goroutine 1 [running]:
github.com/prometheus/prometheus/promql.NewActiveQueryTracker(0x24deddb, 0x5, 0x14, 0x2c635a0, 0xc000613a70, 0x2c635a0)
	/app/promql/query_logger.go:115 +0x48c
main.main()
	/app/cmd/prometheus/main.go:362 +0x5229
```

**Comment by amnonh** [comment] 2020-11-02 17:54
@dyasny first, though it's not a bug, you should avoid running docker as root.
Second, are you using an external directory for Prometheus? if so please make sure it exists and with the right permissions.

please include the start-all.sh command you are using

**Comment by dyasny** [comment] 2020-11-02 17:59
I managed to work around this by setting everything to 777. What would be the actual right permissions?

**Comment by amnonh** [comment] 2020-11-02 18:06
unless there is a good reason, you should run docker with a non-root user, in that case the directory should be owned (or at least have enough permission) by the user running docker.

Please take a look at the docker documentation on how to run docker as non-root

**Comment by amnonh** [comment] 2020-11-02 18:10
Closing as not a bug

**Closed as completed by amnonh** 2020-11-02 18:10 UTC
Labels: bug
