### ISSUE TITLE
Materialized view counters are comulative instead of rates

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla-monitoring#987] opened 2020-07-06 10:12 UTC
scylla-version=2019.1
monitoring-version=master (note sure this is correct)

![image](https://user-images.githubusercontent.com/1017210/86582464-53c47f00-bf8a-11ea-8b20-83bfee448e69.png)

Looks like a missing rate() function

**Comment by amnonh** [comment] 2020-07-06 10:45
Duplicate of #902

**Closed as completed by amnonh** 2020-07-06 10:45 UTC
