### ISSUE TITLE
Alerts: Alerts for high load and latency are not giving host /cluster details - related to #923 [proposed label] User-request 

### ISSUE THREAD

**Issue by albertjosearaujo** [scylladb/scylla-monitoring#934] opened 2020-05-14 12:27 UTC
scylla-version=2019.1.7-0.20200328.c8f0d16d2
monitoring-version=3.1
User creating a new customized alert, wants label to be shown into alert.

@amnonh 
Referencing from https://github.com/scylladb/scylla-monitoring/issues/923, user reports even after changing the expression to include ```by (intance) ```  , is not seeing any alerts even if load went above the threshold. Still get this after change the expression - no host ip  : 

high load:
``` - alert: HighLoad
  expr: avg(scylla_reactor_utilization) by (instance) > 30 
  for: 5m
  labels:
   severity: warning
  annotations:
   summary: “High Load Average 5m (instance {{ $labels.instance }})”
   description: “CPU load is > 30%\n VALUE = {{ $value }}\n LABELS: {{ $labels }}”
 - alert: HostUnusualDiskReadLatency
  expr: histogram_quantile(0.95, sum(rate(scylla_storage_proxy_coordinator_read_latency_bucket[5m])) by (le)) > 20000 
  for: 5m
  labels:
   severity: warning
  annotations:
   summary: “Host unusual disk read latency (instance {{ $labels.instance }})”
   description: “Disk latency is growing (read operations > 20ms)\n VALUE = {{ $value }}\n LABELS: {{ $labels }}”
 - alert: HostUnusualDiskWriteLatency
  expr: histogram_quantile(0.95, sum(rate(scylla_storage_proxy_coordinator_write_latency_bucket[5m])) by (le)) > 10000 
  for: 5m
  labels:
   severity: warning
  annotations:
   summary: “Host unusual disk write latency (instance {{ $labels.instance }})”
   description: “Disk latency is growing (write operations > 100ms)\n VALUE = {{ $value }}\n LABELS: {{ $labels }}”
```

![image](https://user-images.githubusercontent.com/63905044/81932652-7ce81500-95c2-11ea-8eac-3c6a7b5650f4.png)

latency rule : 
```  - alert: HostUnusualDiskReadLatency
  expr: histogram_quantile(0.95, sum(rate(scylla_storage_proxy_coordinator_read_latency_bucket[5m])) by (le)) > 20000 
  for: 5m
  labels:
   severity: warning
  annotations:
   summary: “Host unusual disk read latency (instance {{ $labels.instance }})”
   description: “Disk latency is growing (read operations > 20ms)\n VALUE = {{ $value }}\n LABELS: {{ $labels }}”
 - alert: HostUnusualDiskWriteLatency 
```

![image](https://user-images.githubusercontent.com/63905044/81935578-3ba63400-95c7-11ea-8f85-933c1fa4c59c.png)

**Comment by amnonh** [comment] 2020-05-14 14:20
@albertjosearaujo the description does not match your screenshot.
you say they don't see any alert, but you add a screenshot with an alert without labels.
So which is it?

your capture includes the wrong quote type, but I assume that it was copied from an email.

As this still seems like a configuration issue, I would start by debugging it gradually.
First, make sure that you see an alert by setting the summary and description to something simple and set the duration to 30s (so you'll get an alert quickly).
Once you see the alert, change the summary and description and see that you are getting the message you like.

Then you should be able to set the duration correctly.

**Comment by amnonh** [comment] 2020-06-02 17:28
@albertjosearaujo can we close this?

**Comment by amnonh** [comment] 2020-06-10 07:17
Closing as not a bug, please re-open if needed

**Closed as completed by amnonh** 2020-06-10 07:17 UTC
