### ISSUE TITLE
Alternator metrics not accounted for Requests/s

### ISSUE THREAD

**Issue by hopugop** [scylladb/scylla-monitoring#1776] opened 2022-08-14 16:30 UTC
*Installation details*
Panel Name: Requests/s
Dashboard Name: Overview
Scylla-Monitoring Version: 4.0.0
Scylla-Version: 5.0.1

Alternator metrics not accounted for Requests/s on the Overview panel. The panel formula encompasses CQL and Thrift protocols: 
https://github.com/scylladb/scylla-monitoring/blob/scylla-monitoring-4.0.0/grafana/build/ver_5.0/scylla-overview.5.0.json#L910

On this screenshot, captured during an Alternator-only stress test, we clearly see the cluster is doing thousands of requests while the `Requests/s` panel shows only 5.
![image](https://user-images.githubusercontent.com/1693866/184545795-ce4156b3-f08b-446c-912f-13bba70f4e94.png)

Alternator-specific panel confirms requests are being ran on that API:
![image](https://user-images.githubusercontent.com/1693866/184545952-067b449e-e62c-451c-8c2b-20fdb6de941e.png)

**Comment by amnonh** [comment] 2022-08-16 13:57
Closing as not a bug, alternator has it's own dashboard and we do not mix cql and alternator metrics. reopen if you think it's needed

**Comment by mykaul** [comment] 2024-03-11 08:01
Re-opening - if Scylla is working at 'Alternator mode' (since you can't mix CQL and Alternator), we should make the default overview - the Alternator's.

**Comment by amnonh** [comment] 2024-05-12 12:30
Fixed by #2226

**Closed as completed by amnonh** 2024-05-12 12:30 UTC
Labels: bug, area/alternator
