### ISSUE TITLE
Alerts: Alerts for high load and latency are not giving host /cluster details

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#923] opened 2020-05-11 15:49 UTC

**Comment by tzach** [comment] 2020-05-11 15:51
@amnonh this probably valid for all alerts

**Comment by amnonh** [comment] 2020-05-11 16:03
it should contain instance label, is there an example that it is not?

**Comment by albertjosearaujo** [comment] 2020-05-11 17:03
@amnonh , not sure if is this  what you wanted.

![image](https://user-images.githubusercontent.com/63905044/81589612-efbd7a00-938f-11ea-8c7d-b9289f844ed4.png)

**Comment by amnonh** [comment] 2020-05-11 17:21
@albertjosearaujo 
This is not part of scylla-monitoring latest release.
What monitoring version are you using?

**Comment by albertjosearaujo** [comment] 2020-05-11 17:39
> @albertjosearaujo
> This is not part of scylla-monitoring latest release.
> What monitoring version are you using?

```[root@ip-10-151-44-159 scylla-monitoring-scylla-monitoring-3.1]```

**Comment by amnonh** [comment] 2020-05-11 20:22
It does not seems to be Scylla-monitoring own rule files, can you check Prometheus rules?
you can do that with the prometheus dashboard:
http://{ip}:9090/rules
Where {ip} is the IP of the machine running the monitoring.

Few other things that may happen, is it possible that you copied the `prometheus/prometheus.rules.yml` from an older version or from somewhere else?
The content of it should be:
https://raw.githubusercontent.com/scylladb/scylla-monitoring/branch-3.1/prometheus/prometheus.rules.yml

To make sure what version you are currently running you can always run:
`./start-all.sh --version`

**Comment by albertjosearaujo** [comment] 2020-05-12 15:23
> It does not seems to be Scylla-monitoring own rule files, can you check Prometheus rules?
> you can do that with the prometheus dashboard:
> http://{ip}:9090/rules
> Where {ip} is the IP of the machine running the monitoring.
> 
> Few other things that may happen, is it possible that you copied the `prometheus/prometheus.rules.yml` from an older version or from somewhere else?
> The content of it should be:
> https://raw.githubusercontent.com/scylladb/scylla-monitoring/branch-3.1/prometheus/prometheus.rules.yml
> 
> To make sure what version you are currently running you can always run:
> `./start-all.sh --version`

Following prometheus rules being used.
Just to mention, is this a new customized alert, not a standard one from Scylla

```
- alert: HighLoad
  expr: avg(scylla_reactor_utilization) > 30 
  for: 5m
  labels:
   severity: warning
  annotations:
   summary: “High Load Average 5m (instance {{ $labels.instance }})”
   description: “CPU load is > 30%\n VALUE = {{ $value }}\n LABELS: {{ $labels }}”
 - alert: HostUnusualDiskReadLatency
  expr: histogram_quantile(0.95, sum(rate(scylla_storage_proxy_coordinator_read_latency_bucket[5m])) by (le)) > 20000 
  for: 5m
  labels:
   severity: warning
  annotations:
   summary: “Host unusual disk read latency (instance {{ $labels.instance }})”
   description: “Disk latency is growing (read operations > 20ms)\n VALUE = {{ $value }}\n LABELS: {{ $labels }}”
 - alert: HostUnusualDiskWriteLatency
  expr: histogram_quantile(0.95, sum(rate(scylla_storage_proxy_coordinator_write_latency_bucket[5m])) by (le)) > 10000 
  for: 5m
  labels:
   severity: warning
  annotations:
   summary: “Host unusual disk write latency (instance {{ $labels.instance }})”
   description: “Disk latency is growing (write operations > 100ms)\n VALUE = {{ $value }}\n LABELS: {{ $labels }}” ```

**Comment by amnonh** [comment] 2020-05-13 10:54
The problem is with the expression. when you avg over all instances it eliminate the instance label,
it should be:
`expr: avg(scylla_reactor_utilization) by (instance) > 30`

**Comment by amnonh** [comment] 2020-05-13 10:54
Closing as not a bug, you can re-open if needed

**Closed as completed by amnonh** 2020-05-13 10:54 UTC
Labels: User-request, Need Info
