### ISSUE TITLE
Scylla Monitoring latency graphs have gaps

### ISSUE THREAD

**Issue by ebenzecri** [scylladb/scylla-monitoring#1988] opened 2023-05-24 16:17 UTC
### Installation details
Instance: n2-highmem-16
Scylla-Monitoring Version: 4.4.0

### Issue
Even using `--no-cas-cdc`, latency graphs are still "funny".
 
<img width="1371" alt="funny_charts" src="https://github.com/scylladb/scylla-monitoring/assets/62569533/84b477b4-127f-438e-aa69-9032bbb1afe8">

**Comment by mykaul** [comment] 2023-05-24 16:22
Cluster details?

**Comment by ebenzecri** [comment] 2023-05-24 17:58
@mykaul Here are the details:
```
Cluster size: 36 nodes
Instance type: n2-highmem-32
Scylla version: 2021.1.16-0.20221022.3224379e7
```

@amnonh is aware of this issue that's why I opened it :)

Thanks!

**Comment by amnonh** [comment] 2023-05-28 07:32
@ebenzecri can you please open an enterprise issue with the relevent details, I would like to look at the server

**Comment by amnonh** [comment] 2023-06-03 14:02
@ebenzecri can we close this as not a bug?

**Comment by vladzcloudius** [comment] 2023-06-08 17:36
Not a bug. Latency graphs (histograms) are known to have "gaps" if there is no traffic in the corresponding SG.

**Closed as not planned by vladzcloudius** 2023-06-08 17:36 UTC
Labels: bug
