### ISSUE TITLE
Dashboards for scylla branch-3.2 don't display data due to errors

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylla-monitoring#782] opened 2019-12-10 04:40 UTC
Most of the Dashboards for scylla branch-3.2 are empty and don't display data on panels due to errors:
* "parse error at char 1: unexpected character: '$'"
* Templating init failed Cannot read property 'ctor' of undefined
* "parse error at char 118: unexpected "[" in grouping opts, expected label"

This happened if first time open appropriate dashboard. if open master branch dashboard first, and then open same dashboard for branch-3.2, then data appeared.
See errors in screenshots
![IO-dashboard_error](https://user-images.githubusercontent.com/44991177/70496289-ab5c5280-1b41-11ea-88d8-b919784bfd57.png)
![IO-dashboard_error_1](https://user-images.githubusercontent.com/44991177/70496290-ab5c5280-1b41-11ea-938b-455e9e8542f6.png)
![Overview](https://user-images.githubusercontent.com/44991177/70496291-ab5c5280-1b41-11ea-9ca0-d84e35c4939c.png)
![Overview_1](https://user-images.githubusercontent.com/44991177/70496292-abf4e900-1b41-11ea-98c5-330f10a51a1f.png)

This messages found in logs:
t=2019-12-10T04:36:20+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/api/datasources/proxy/1/api/v1/query_range status=400 remote_addr=18.195.97.164 time_ms=1 size=128 referer="http://34.244.71.62:3000/d/cql-3-2/scylla-cql?orgId=1"
t=2019-12-10T04:36:20+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/api/datasources/proxy/1/api/v1/query_range status=400 remote_addr=18.195.97.164 time_ms=1 size=128 referer="http://34.244.71.62:3000/d/cql-3-2/scylla-cql?orgId=1"
t=2019-12-10T04:36:20+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/api/datasources/proxy/1/api/v1/query_range status=400 remote_addr=18.195.97.164 time_ms=1 size=127 referer="http://34.244.71.62:3000/d/cql-3-2/scylla-cql?orgId=1"

**Comment by amnonh** [comment] 2019-12-10 07:41
@aleksbykov I cannot reproduce it with simple tests. can you please add the command line you used to start and the scylla_server file you used?

**Comment by amnonh** [comment] 2019-12-10 07:52
This is a side effect of using square brackets around the ip address (I think it was done in QA for ipv6 support).

A metric example is now:

scylla_cache_bytes_total{instance="[10.0.11.1]",job="scylla",shard="0"}

**Comment by amnonh** [comment] 2019-12-10 08:36
Found the issue, version mismatch between branch 3.0 and master

**Comment by amnonh** [comment] 2019-12-10 08:57
Fixed in 3.0.4

**Closed as completed by amnonh** 2019-12-10 08:57 UTC

**Comment by bentsi** [comment] 2019-12-15 13:36
@amnonh is this `branch 3.0` only issue?

**Comment by amnonh** [comment] 2019-12-15 13:45
it is, and it is solved in 3.0.4 or 3.1
