### ISSUE TITLE
Copy the help text from scylla metrics onto prometheus help (visible in hover over)

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla-monitoring#227] opened 2017-09-10 10:20 UTC

**Comment by tzach** [comment] 2017-09-10 11:08
@amnonh can you please take a look?

**Comment by tzach** [comment] 2017-10-03 12:24
Current descriptions give very little or no extra information

**Comment by amnonh** [comment] 2017-12-17 08:47
@tzach can you either close this issue or comment on the patch if you prefer a different implementation

**Comment by tzach** [comment] 2017-12-19 09:42
Help text from scylla metrics currently repeating the metric name does not add information.
Adding it to the hover text is not helping the user. Once we have useful info, we can revisit this

**Comment by amnonh** [comment] 2018-02-04 11:14
@tzach @slivne please close the issue or update it

**Comment by nyh** [comment] 2018-05-08 08:29
@amnonh @tzach I think this issue is very important. I often look at a metric and ask myself what does this metric really measure, what it includes and doesn't include, and what its units are. We just had today a heated discussion on the mailing list what "background writes" count, just as one example.
However, I agree with @tzach that the information must be **useful** information. Currently, we have the explanation for background writes as "number of currently pending background write requests". No shit, Sherlock :-) This doesn't answer any of the questions a user might have (and were raised on the mailing list  today) what are background writes, or that writes change from being background to forground. It's not even clear at what level a "write request" is - is this a disk-level write request? A replica-level request? A coordinator-level request (a request from a client)?

I think ideally the user should be able to get a whole paragraph - perhaps even a link to a longer document or popup frame or whatever - explaining exactly what this metric means.

**Comment by tzach** [comment] 2018-05-08 08:38
@nyh the problem is real, but there is no easy solution.
The best way to move forward sending individual PRs, improving one metric description at a time.

**Comment by nyh** [comment] 2018-05-08 08:58
@tzach, I think first there needs to be a policy what these "descriptions" are expected to be - should they be a half-sentence vague explanation, like today? Should they be a paragraph-long explanation? A page-long? Maybe we need more than one of the above?
The answer to this question is also related to another policy - of what we do with these "descriptions". Are they shown in a list? In a tiny popup string? In a large popup frame? In a reference document?
I don't think we should decide this one description at a time.

**Closed as completed** 2019-12-11 14:52 UTC
