### ISSUE TITLE
Latencies percentiles aggregations may give misleading results

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla-monitoring#1886] opened 2023-02-07 02:18 UTC
*Installation details*
Panel Name: latenices aggregations
Dashboard Name: Detailed, Overview, Advanced
Scylla-Monitoring Version: 4.1.0
Scylla-Version: irrelevant

*Description*
Our percentiles macros are averaging Ps (e.g. P99) across shads/nodes/DCs.
This can only give a result close to the real P99 if each separate per-shard Ps are close to one another.

However if a tail latency on some shards is significantly higher than on others and if higher Ps tail latency of all shards is high this will return a much lower value than the real one.

In general, a much more realistic approximation for a P in the whole system given Ps on separate shards in a `max` function. 
It will approximate the real value from the top and it may get scary but when we look at Ps we want to see the ugly truth instead of a pretty picture. ;)

**Comment by vladzcloudius** [comment] 2023-02-07 02:19
@avikivity @fee-mendes FYI

**Comment by amnonh** [comment] 2023-02-07 11:40
In fact, we calculate the P95, P99 on each level seperately, i.e.
calculate at a shard level, at a node level at a DC level and at a cluster level.

For example, to answer the question what is the P99 of a cluster, we calculate a histogram of all latencies from all shards and get the P99 from that histogram.

**Comment by isburmistrov** [comment] 2023-02-07 12:08
I'm confused @amnonh. Is this expression that's being ultimately used for e.g. instance latency?

`histogram_quantile(0.99, sum(rate(scylla_storage_proxy_coordinator_read_latency_bucket{scheduling_group_name!~"atexit|gossip|mem_compaction|memtable|streaming|background_reclaim|compaction|main|memtable_to_cache"}[60s])) by (cluster, dc, instance, scheduling_group_name, le))`

**Comment by amnonh** [comment] 2023-02-07 12:11
Latencies calculations are done with recording rules, we have one for each level for example we have `rlatencyp95` rule for shard, for node, for dc and for cluster.
(we actually have two for each so we can mark to datadog what to scrap)

**Comment by isburmistrov** [comment] 2023-02-07 12:18
Can you share what happens when we calculate e.g. per-instance latency?

> For example, to answer the question what is the P99 of a cluster, we calculate a histogram of all latencies from all shards and get the P99 from that histogram.

Because this is not clear what means exactly.

**Comment by amnonh** [comment] 2023-02-07 12:36
For a shard view we are calclating:
```
  - record: rlatencyp95
    expr: histogram_quantile(0.95, sum(rate(scylla_storage_proxy_coordinator_read_latency_bucket{shard=~".+", scheduling_group_name=~"atexit|gossip|mem_compaction|memtable|streaming|background_reclaim|compaction|main|memtable_to_cache"}[60s])) by (cluster, dc, instance, shard, scheduling_group_name, le))
    labels:
      by: "instance,shard"
```

So we are calculating the latency for each of the shards

**Comment by amnonh** [comment] 2023-02-07 13:02
I tend to close as not a bug, but maybe there's somthing that I am missing.

Just to conclude, let's talk about p99 write latencies of the cluster.
if you look at all the writes in the last minute, let's say there where 1000 writes.
you order all 1000 in a descending order, the value at position 10, is your p99.

But you need to take all queries from all shards and nodes to calculat the cluster p99

**Comment by vladzcloudius** [comment] 2023-02-07 15:48
> I tend to close as not a bug, but maybe there's somthing that I am missing.
> 
> Just to conclude, let's talk about p99 write latencies of the cluster. if you look at all the writes in the last minute, let's say there where 1000 writes. you order all 1000 in a descending order, the value at position 10, is your p99.
> 
> But you need to take all queries from all shards and nodes to calculat the cluster p99

That's correct, @amnonh. And since you don't know how the sorting is going to be node-wide and cluster-wide you hit the problem I've described above by averaging.

**Comment by vladzcloudius** [comment] 2023-02-07 15:51
> In fact, we calculate the P95, P99 on each level seperately, i.e. calculate at a shard level, at a node level at a DC level and at a cluster level.
> 
> For example, to answer the question what is the P99 of a cluster, we calculate a histogram of all latencies from all shards and get the P99 from that histogram.

Do we? I strongly doubt that, @amnonh.
You get histograms for shard-level only from Scylla.
And from what I saw what you do next in Prometheus - you average:

```
"targets":[
               {
                  "expr":"avg(rlatencyp99{by=\"cluster\", cluster=~\"$cluster|^$\",scheduling_group_name!=\"streaming\"}>0)",
                  "intervalFactor":1,
                  "legendFormat":"",
                  "refId":"A",
                  "instant":true,
                  "step":4
               }
            ],
```

**Comment by vladzcloudius** [comment] 2023-02-07 16:27
> For a shard view we are calclating:
> 
> ```
>   - record: rlatencyp95
>     expr: histogram_quantile(0.95, sum(rate(scylla_storage_proxy_coordinator_read_latency_bucket{shard=~".+", scheduling_group_name=~"atexit|gossip|mem_compaction|memtable|streaming|background_reclaim|compaction|main|memtable_to_cache"}[60s])) by (cluster, dc, instance, shard, scheduling_group_name, le))
>     labels:
>       by: "instance,shard"
> ```
> 
> So we are calculating the latency for each of the shards

This doesn't make sense: based on the expression for `instance` for instance we were supposed to see the P99 close to the "sum" on P99s from shard:

```
  - record: rlatencyp99
    expr: histogram_quantile(0.99, sum(rate(scylla_storage_proxy_coordinator_read_latency_bucket{scheduling_group_name!~"atexit|gossip|mem_compaction|memtable|streaming|background_reclaim|compaction|main|memtable_to_cache"}[60s])) by (cluster, dc, instance, scheduling_group_name, le))
    labels:
      by: "instance"
      level: "1"
```

But this is not what we see. We don't even see a proper bucketing on the per instance level too:

![image](https://user-images.githubusercontent.com/6103981/217303449-23c28d66-2d3e-4058-ba1d-427e249cc0c9.png)
![image](https://user-images.githubusercontent.com/6103981/217303492-1f9cbed4-3cbb-4c03-87a2-735c1180f6eb.png)
![image](https://user-images.githubusercontent.com/6103981/217303518-1781384d-e312-49be-bd21-2797c5b6eb2c.png)

As you can see the system has 44 shards, so I would expect that the cross shard P99 would be as the highest or at worst the second highest shard.

However the aggregated value looks like an average.

@amnonh comments?

**Comment by amnonh** [comment] 2023-02-07 16:40
@vladzcloudius What you describe is not how you calculate p99.

See my explenation, we get per-shard histograms from Scylla and then use recording rules to create a calculate value for shard, node, dc, cluster with an additional label that is called ```by``` avg over that is just to get the label, it doesn't do avg

**Comment by vladzcloudius** [comment] 2023-02-07 17:13
> @vladzcloudius What you describe is not how you calculate p99.
> 
> See my explenation, we get per-shard histograms from Scylla and then use recording rules to create a calculate value for shard, node, dc, cluster with an additional label that is called `by` avg over that is just to get the label, it doesn't do avg

@amnonh Please, see my post above: https://github.com/scylladb/scylla-monitoring/issues/1886#issuecomment-1421058473

Any comments about the data on screenshots?

**Comment by amnonh** [comment] 2023-02-07 17:47
> > @vladzcloudius What you describe is not how you calculate p99.
> > See my explenation, we get per-shard histograms from Scylla and then use recording rules to create a calculate value for shard, node, dc, cluster with an additional label that is called `by` avg over that is just to get the label, it doesn't do avg
> 
> @amnonh Please, see my post above: [#1886 (comment)](https://github.com/scylladb/scylla-monitoring/issues/1886#issuecomment-1421058473)
> 
> Any comments about the data on screenshots?

yes, that p99 is not intuitive and if you have one or two shards with high p99 out of many, it just mean you cannot predict what the p00 of the cluster

**Comment by vladzcloudius** [comment] 2023-02-07 17:54
> > > @vladzcloudius What you describe is not how you calculate p99.
> > > See my explenation, we get per-shard histograms from Scylla and then use recording rules to create a calculate value for shard, node, dc, cluster with an additional label that is called `by` avg over that is just to get the label, it doesn't do avg
> > 
> > 
> > @amnonh Please, see my post above: [#1886 (comment)](https://github.com/scylladb/scylla-monitoring/issues/1886#issuecomment-1421058473)
> > Any comments about the data on screenshots?
> 
> yes, that p99 is not intuitive and if you have one or two shards with high p99 out of many, it just mean you cannot predict what the p00 of the cluster

It's not counterintuitive, @amnonh  - it looks very wrong.
In the example above a lot more than 1% of P99 were above 20ms:

![image](https://user-images.githubusercontent.com/6103981/217327713-fd822dab-ebe9-461b-be2c-65aa1d5a4c89.png)


3 out of 44 shards to be specific. 
And 10 out of 44 them are above 8ms. This is more than 20%!

**Comment by isburmistrov** [comment] 2023-02-07 18:03
Do we still have all the raw data that recording rules are based on?
Can we compute P99 using prom query on raw data & compare?

I have a feeling that recording rules get executed too early and hence
compute data based on incomplete per-shard data.

Comparing with raw query will highlight if there is an issue indeed.

**Comment by vladzcloudius** [comment] 2023-02-07 18:14
First of all this is how per-shard looks like:

![image](https://user-images.githubusercontent.com/6103981/217330681-44a031e3-2678-4f68-8cbd-f65df03fb5b2.png)

Ouch, @amnonh

**Comment by vladzcloudius** [comment] 2023-02-07 18:21
This is more like it:

![image](https://user-images.githubusercontent.com/6103981/217332293-5938295e-9b3a-4db4-85f0-021967de54e8.png)


@amnonh FYI

**Comment by vladzcloudius** [comment] 2023-02-07 18:24
But even that makes little sense. I was expecting the P99 to be closer to 30ms

**Comment by vladzcloudius** [comment] 2023-02-07 18:29
I'm still not getting the role of the "sum" in the expression above.
@amnonh could you, please, elaborate?

**Comment by isburmistrov** [comment] 2023-02-07 18:38
> But even that makes little sense. I was expecting the P99 to be closer to
30ms

It depends on latency distribution in the shards, p99 for the instance
aggregation can indeed look weird.

Assume toy example when we have 50 shards (for simplicity), each of them
processed 100 requests. In 49 shards 1 request took 100ms, the rest - 5ms.
In the last 50th shard all requests took 5ms.
So 49 out of 50 shards will have p99=100ms, but overall p99 across all
shards will be 5ms.

**Comment by vladzcloudius** [comment] 2023-02-07 18:39
> I'm still not getting the role of the "sum" in the expression above. @amnonh could you, please, elaborate?

NM. I figured - it's just a PromQL syntax.
So, the only question is why the raw PromQL expression returns us x3 higher value than the "recordings", @amnonh ?

**Comment by amnonh** [comment] 2023-02-07 18:50
In 4.2 release I've lowered the evaluation interval to 20s```evaluation_interval: 20s``` that should give closer results between the recording rules and on the fly calculation.

**Comment by vladzcloudius** [comment] 2023-02-07 18:52
I used the same 60 seconds in the example above just like the aggregation does.

**Comment by amnonh** [comment] 2023-02-07 18:56
@vladzcloudius two different things: one is the duration you are calculating the rate (60s), second is how often you calcualte the recording rules.
This configuration, is taken from prometheus/prometheus.yml.template and then copied to prometheus/build/prometheus.yml

**Comment by vladzcloudius** [comment] 2023-02-07 19:05
> In 4.2 release I've lowered the evaluation interval to 20s`evaluation_interval: 20s` that should give closer results between the recording rules and on the fly calculation.

Not sure how this is going to improve the result. 
AFAIU you are not loosing samples or averaging while you are calculating the "recording". By decreasing the `evaluation_interval` you are simply going to do smaller amount of calculations more frequently, don't you, @amnonh ?

**Comment by amnonh** [comment] 2023-02-08 08:35
I run a test on my laptop and used 4 cores, this is what I see with an evaluation_interval of 20:
![image](https://user-images.githubusercontent.com/2118079/217476048-25e42c5a-9d9c-4394-91b4-b4ba3a8df296.png)
lower resolution (ie. longer evaluation interval) would tend to flatten curves.

Give 4.2.1 a chance

**Comment by amnonh** [comment] 2023-02-09 12:01
Also a duplicate of #1815

**Comment by amnonh** [comment] 2023-02-16 09:34
Closing in favor of  #1815

**Closed as completed by amnonh** 2023-02-16 09:34 UTC
Labels: Need Info
