### ISSUE TITLE
scylla-manager-metrics dashboard is empty even when the manager exports prometheus data

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylla-monitoring#1300] opened 2021-03-03 08:02 UTC
*Installation details*
Dashboard Name: scylla-manager-metrics
Scylla-Monitoring Version: 3.6.1
Scylla-Version: 4.5.dev-0.20210301.baf5d0563
Scylla Manager version: 666.dev-0.20210302.5e497dd0

The manager dashboard remains empty: http://3.239.199.222:3000/d/manager-2-2/scylla-manager-metrics?orgId=1
Even though I started the monitor with the with the `-l` flag:
```
./start-all.sh             -D "--label RunByUser=shlomibalalis --label TestName=mgmt_cli_test.MgmtCliTest.test_manager_sanity --label TestId=0b308190-33d4-4586-84e7-c11c0929133b --label version=manager-master --label JenkinsJobTag=jenkins-manager-master-staging-centos-sanity-test-staging-25 --label NodeType=monitor --label keep_action= --label Name=manager-regression-master-monitor-node-0b308190-1 --label NodeIndex=1"             -s `realpath "/home/centos/sct-monitoring/scylla-monitoring-src/config/scylla_servers.yml"`             -n `realpath "/home/centos/sct-monitoring/scylla-monitoring-src/config/node_exporter_servers.yml"`             -d `realpath "/home/centos/sct-monitoring/scylla-monitoring-data"` -l -v master,master -b "-web.enable-admin-api"
```

The manager's metrics: http://3.239.199.222:5090/metrics

**Comment by amnonh** [comment] 2021-03-03 11:32
if you log in to Prometheus targets you will see that scylla-manager is not configure with the right ports:
http://3.239.199.222:9090/targets

![image](https://user-images.githubusercontent.com/2118079/109799475-c58dbf00-7c24-11eb-8689-e329a4bf0f91.png)
Fix your scylla-manager file configuration, closing as this is a configuration issue and not a bug

**Closed as completed by amnonh** 2021-03-03 11:32 UTC
Labels: configuration
