### ISSUE TITLE
Discrepancy between requests/second and 'reads.

### ISSUE THREAD

**Issue by pveentjer** [scylladb/scylla-monitoring#1519] opened 2021-08-21 08:01 UTC
*Installation details*
Panel Name: Cluster Overview
Dashboard Name: Overview
Scylla-Monitoring Version: 3.6.4
Scylla-Version: 4.4.3

There is a discrepancy between the requests/second and the reads. 

![image](https://user-images.githubusercontent.com/105243/130315038-876e6a81-9669-4ec2-aa81-a6f15db1309a.png)

So one say almost 3k and the the other 2.4/2.5M and sometimes the 'requests/s' drops a lot (e.g. 1.9M) but I don't see any dip in the 'reads' panel. 

Initially I thought the discrepancy is caused by the some kind of slow windowed average. But after more than 10m, the 'requests/s' panel has not caught up 

More info will follow as soon as the benchmark has completed and I have the locally calculated throughput numbers. The actual numbers should be close to 3M based on what I'm seeing from scylla-bench. I got similar numbers with cassandra-test on this setup.

Another problem is that the 'reads' panel is a factor 1000 off. It shows 3kops, but actually the number should be around 3000 kops (3M). 

Update:

I think the 'reads panel' is showing the throughput of a single shard, or the average throughput over all shards; not the total throughput of a single node.

**Comment by pveentjer** [comment] 2021-08-21 08:16
More weird behavior.

You can see screenshots here. The first screenshot s with 'by cluster'.

![image](https://user-images.githubusercontent.com/105243/130315503-503a2aab-edf4-4f04-83f9-047522c9df7d.png)

The second screenshot is  'by instance/shard'

![image](https://user-images.githubusercontent.com/105243/130315515-cd84d7c8-675a-4c63-adf3-3cc3e058d2aa.png)

As you can see, the "requests served per cluster - Coordinator" has not changed at all. It seems it is not adding the requests/second of every shard, but it is taking the average over all shards. Since I have 92 shards, the displayed throughput is just 1/92 of the total amount. 

This is a not a temp glitch; so waiting some time for the 'by cluster' screen to properly update doesn't resolve the problem.

**Comment by pveentjer** [comment] 2021-08-21 08:21
It seems that finally the discrepancy on the first screen has been resolved.

![image](https://user-images.githubusercontent.com/105243/130315708-40f3c12b-abd2-4b4a-b01e-d59d256bd394.png)

**Comment by pveentjer** [comment] 2021-08-21 08:32
I have collected the dump of all Prometheus data so you can have a look yourself. 

https://drive.google.com/file/d/1Ni2SkTPZzAG79HMA1JWjy4Aj88kXyv_b/view?usp=sharing

**Comment by amnonh** [comment] 2021-08-22 14:56
> More weird behavior.
> 
> You can see screenshots here. The first screenshot s with 'by cluster'.
> 
> ![image](https://user-images.githubusercontent.com/105243/130315503-503a2aab-edf4-4f04-83f9-047522c9df7d.png)
> 
> The second screenshot is 'by instance/shard'
> 
> ![image](https://user-images.githubusercontent.com/105243/130315515-cd84d7c8-675a-4c63-adf3-3cc3e058d2aa.png)
> 
> As you can see, the "requests served per cluster - Coordinator" has not changed at all. It seems it is not adding the requests/second of every shard, but it is taking the average over all shards. Since I have 92 shards, the displayed throughput is just 1/92 of the total amount.

I'm trying to reproduce it locally, but in a first glance, you can see in your screenshot that you use the `avg` as an agreggation function instead of the default sum

Would that explain it?
> 
> This is a not a temp glitch; so waiting some time for the 'by cluster' screen to properly update doesn't resolve the problem.

**Comment by amnonh** [comment] 2021-08-22 15:01
I've tested it locally with function set to `sum`
![image](https://user-images.githubusercontent.com/2118079/130359886-d5e94897-b0e6-4f7a-a7bd-73b8b1a96efc.png)

It seems fine, closing as a not a bug, please reopen if you think there is still an issue

**Closed as completed by amnonh** 2021-08-22 15:01 UTC
Labels: bug

**Comment by pveentjer** [comment] 2021-08-22 16:40
Thanks @amnonh. That might explain it.
