### ISSUE TITLE
3.1 Monitoring - OS metrics problem - disks not shown

### ISSUE THREAD

**Issue by yksdb** [scylladb/scylla-monitoring#837] opened 2020-02-26 17:07 UTC
Issue: some or all disks are not present in both Overview and Detailed OS Metrics.

Reported in Scylla 2018.1 and 2019.1 by customers in AWS
Monitoring is 3.0 and 3.1
Node exporter 0.17 (or even earlier)
Internal tickets are 981 and 1690 (cloud)

Attempted to reproduce in AWS with local and EBS disks - can't reproduce (Scylla 2019.1.4 in CentOS 7, ode_exporter version 0.17.0, Monitoring 3.1 in docker).

**Comment by yksdb** [comment] 2020-02-26 17:14
Following images are from ticket 981 where it can be seen that no disk info is present

<img width="744" alt="Screen Shot 2020-02-26 at 10 37 30 AM" src="https://user-images.githubusercontent.com/53574706/75369376-56eb8800-5891-11ea-8280-80b908f27d97.png">
<img width="483" alt="Screen Shot 2020-02-26 at 10 38 22 AM" src="https://user-images.githubusercontent.com/53574706/75369377-57841e80-5891-11ea-9168-8ef4a79ab05b.png">

**Comment by yksdb** [comment] 2020-02-26 17:19
When attempted to reproduce issue with same versions of all components in VMs running in AWS I was able to see both instance disk and EBS attached disk as per attached image.
(vm1 - Scylla 2019.1.4 in CentOS 7, node_exporter 0.17.0, vm2 - Monitoring 3.1 in docker on CentOS 7)

![Screenshot - 2_25_2020 , 3_08_11 PM](https://user-images.githubusercontent.com/53574706/75369486-87cbbd00-5891-11ea-8b09-effbb3df82bd.JPG)

**Comment by amnonh** [comment] 2020-02-26 19:14
This seems like a miss-match between node_exporter, scylla monitoring, and the Prometheus configuration probably due to an upgrade.

Scylla Monitoring 3.0 and onwards, only works with node_exporter 0.17.
Please validate that node_exporter runs the correct version.
Also, please make sure that prometheus.yml (found under `prometheus/build`) is not an older copy from before the upgrade.

You can verify it by pointing your browser to: http://{ip}:9090/config

If there is a `metric_relabel_configs:` part in the config, it's an older version, use a clean installation and it should work.

**Comment by yksdb** [comment] 2020-02-28 18:48
In ticket 981 the customer has upgraded from Monitoring 2.3 to 3.1 but has copied config files in this manner:
cp scylla-grafana-monitoring-2_3/prometheus/ scylla-grafana-monitoring-3.1/prometheus/

which means they got all the following files from 2.3 inside 3.1

prometheus.consul.yml.template
prometheus.rules.yml
prometheus.yml.template
rule_config.yml
scylla_manager_servers.example.yml
scylla_servers.example.yml
scylla_servers.yml

(of course scylla_servers.yml was edited or replaced later)

Advised customer to rebuild the stack afresh following this doc https://docs.scylladb.com/upgrade/upgrade-monitor/upgrade-guide-from-monitoring-2.x-to-monitoring-3.y/
and replace only selected config files as per instructions.

Will update on the outcome.

**Comment by yksdb** [comment] 2020-02-28 18:51
to reproduce the issue:
- perform upgrade as per doc
- copy over whole 'monitoring-2.3/prometheus' directory to new stack
- update scylla_servers.yml
- start 3.1 stack

Result: no disks shown.

 screenshot attached
![Screenshot - 2_28_2020 , 1_30_51 PM](https://user-images.githubusercontent.com/53574706/75578133-538f0280-5a31-11ea-8584-f70da84e4bf2.JPG)

There is some limited functionality even then
![Screenshot - 2_28_2020 , 1_52_24 PM](https://user-images.githubusercontent.com/53574706/75578319-9cdf5200-5a31-11ea-873a-473f82e16834.JPG)

**Comment by amnonh** [comment] 2020-02-28 19:15
As expected, it's simply not something you should do.
Closing as not a bug

**Closed as completed by amnonh** 2020-02-28 19:15 UTC
