### ISSUE TITLE
UID contains illegal characters

### ISSUE THREAD

**Issue by Cary4** [scylladb/scylla-monitoring#1165] opened 2020-12-09 18:18 UTC
scylla-version=4.2
monitoring-version=3.5
dashboard=overview-4-2

Hello,

 I have just updated our development Scylla monitoring to version 3.5. Our Scylla clusters are running version 4.2.1. When watching, docker logs -f agraf, I see this error about every 10 seconds:

lvl=eror msg="failed to save dashboard" logger=provisioning.dashboard type=file name=4.2 error="uid contains illegal characters"

We are using Ubuntu 18.04 

I was wondering if anyone else has seen that, and if there is anything I can do to fix it.

Cary

**Comment by amnonh** [comment] 2020-12-15 08:05
Duplicate of #1130 update to the latest 3.5.x and it should be fixed

**Closed as completed by amnonh** 2020-12-15 08:05 UTC
