### ISSUE TITLE
Alertmanager logs are not clear enough

### ISSUE THREAD

**Issue by mailmahee** [scylladb/scylla-monitoring#1083] opened 2020-10-20 19:15 UTC
while installing the monitoring version for 2020.1.3 i.e. 3.43
we were using docker to bring up all the components. there were some permissions issues on the files and the startall script was not copying all the corresponding files from the monitoring directory to docker. this was the error with which Altrertmanager was failing 

```
level=error ts=2020-10-16T01:16:28.734Z caller=coordinator.go:124 component=configuration msg="Loading configuration file failed" file=/etc/alertmanager/config.yml err="open /etc/alertmanager/config.yml: permission denied"
```

the error is not descriptive enough then I disabled alert manager and then started the Prometheus container and it failed as well. looking into the debug message I understood the issue and updated the necessary permissions with chmod 777 and then Prometheus started and did similar changes and alert manager started as well. it would be great if we can update the alert manager debug logs.

**Comment by amnonh** [comment] 2020-11-19 11:03
@mailmahee the issue title is "Alertmanager startup failing quietly" but the description says that the logs are not clear enough, which is the issue?

**Comment by mailmahee** [comment] 2020-11-27 23:59
@amnonh As I wrote in detail above - the debug messages will be descriptive if we simply add a few more debug messages saying a little more than `permission denied`  - maybe what operation was being performed (like copying the config file etc and that permissions are not enough).

**Comment by amnonh** [comment] 2020-12-15 08:47
As the issue is with the alertmanager logs, we don't have control over it, so I'm closing this issue, please re-open if there is something we can do in the scylla monitoring

**Closed as completed by amnonh** 2020-12-15 08:47 UTC
Labels: bug, Need Info
