### ISSUE TITLE
hints sent is cumulative from node start time, but displayed as rate

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla-monitoring#986] opened 2020-07-06 10:10 UTC
scylla-version=2019.1
monitoring-version=master (not sure this is correct)

![image](https://user-images.githubusercontent.com/1017210/86582194-ef092480-bf89-11ea-9d64-0c3f89801671.png)

This looks like slowly growing counters with node restarts, not real rates.

**Comment by amnonh** [comment] 2020-07-06 10:42
Duplicate of #865

**Closed as completed by amnonh** 2020-07-06 10:42 UTC
