### ISSUE TITLE
System master dashboards were not created. Only default 4.3

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylla-monitoring#1445] opened 2021-06-16 04:04 UTC
*Installation details*
Scylla-Monitoring Version: 3.7.1
Scylla-Version:Scylla version 4.6.dev-0.20210531.b0c22f2e39 with build-id 6a2a6e52891ef3f81d9a844a9b84d45da27c6cbe

scylla monitoring should start with master set of dashboards. But started with only 4.3 dashboards:
![Screenshot from 2021-06-16 10-54-06](https://user-images.githubusercontent.com/44991177/122155465-39c93700-ce91-11eb-881f-f348a3630996.png)

command which was used to start scylla-monitoring:  
```
./start-all.sh             -D "--label RunByUser=timer --label TestName=longevity_test.LongevityTest.test_custom_time --label TestId=05e95283-ed77-47ba-86e5-94543ebc8334 --label version=scylla-master --label JenkinsJobTag=jenkins-scylla-master-longevity-longevity-50gb-3days-80 --label NodeType=monitor --label keep_action= --label Name=longevity-tls-50gb-3d-master-monitor-node-05e95283-1 --label NodeIndex=1"             -s `realpath "/home/centos/sct-monitoring/scylla-monitoring-src/config/scylla_servers.yml"`             -n `realpath "/home/centos/sct-monitoring/scylla-monitoring-src/config/node_exporter_servers.yml"`             -N `realpath "/home/centos/sct-monitoring/scylla-monitoring-src/config/scylla_manager_servers.yml"` \             -d `realpath "/home/centos/sct-monitoring/scylla-monitoring-data"` -l -v master,master -b "-web.enable-admin-api"
```
Livemonitoring:  ssh -i ~/.ssh/scylla-qa-ec2 centos@13.51.238.247, http://13.51.238.247:3000

i manuall run commands on monitor node:
`.kill-all.sh`
```
./start-all.sh             -D "--label RunByUser=timer --label TestName=longevity_test.LongevityTest.test_custom_time --label TestId=05e95283-ed77-47ba-86e5-94543ebc8334 --label version=scylla-master --label JenkinsJobTag=jenkins-scylla-master-longevity-longevity-50gb-3days-80 --label NodeType=monitor --label keep_action= --label Name=longevity-tls-50gb-3d-master-monitor-node-05e95283-1 --label NodeIndex=1"             -s `realpath "/home/centos/sct-monitoring/scylla-monitoring-src/config/scylla_servers.yml"`             -n `realpath "/home/centos/sct-monitoring/scylla-monitoring-src/config/node_exporter_servers.yml"`             -N `realpath "/home/centos/sct-monitoring/scylla-monitoring-src/config/scylla_manager_servers.yml"` \             -d `realpath "/home/centos/sct-monitoring/scylla-monitoring-data"` -l -v master,master -b "-web.enable-admin-api"
```

result stay the same. only dashboard 4.3 were created

**Comment by amnonh** [comment] 2021-06-17 07:22
I've tried it myself, the original command didn't work, after cleaning the command from the slashes and spaces I run it again:
```
./start-all.sh -D "--label RunByUser=timer --label TestName=longevity_test.LongevityTest.test_custom_time --label TestId=05e95283-ed77-47ba-86e5-94543ebc8334 --label version=scylla-master --label JenkinsJobTag=jenkins-scylla-master-longevity-longevity-50gb-3days-80 --label NodeType=monitor --label keep_action= --label Name=longevity-tls-50gb-3d-master-monitor-node-05e95283-1 --label NodeIndex=1" -s `realpath "/home/centos/sct-monitoring/scylla-monitoring-src/config/scylla_servers.yml"` -n `realpath "/home/centos/sct-monitoring/scylla-monitoring-src/config/node_exporter_servers.yml"` -N `realpath "/home/centos/sct-monitoring/scylla-monitoring-src/config/scylla_manager_servers.yml"` -d `realpath "/home/centos/sct-monitoring/scylla-monitoring-data"` -l -v master -b "-web.enable-admin-api"

```

And now it's working, closing as not a bug but a problem in calling to  `start-all.sh command`

**Closed as completed by amnonh** 2021-06-17 07:22 UTC
Labels: bug
